export type ContentKeywordTarget = {
  route: string
  pageType:
    | 'home'
    | 'listing'
    | 'category'
    | 'tour'
    | 'destination'
    | 'blog'
    | 'company'
  primaryKeyword: string
  secondaryKeywords: string[]
  searchIntent:
    | 'commercial'
    | 'transactional'
    | 'informational'
    | 'navigational'
  indexable: boolean
  notes?: string
}

export const contentKeywordTargets: ContentKeywordTarget[] = [
  {
    route: '/',
    pageType: 'home',
    primaryKeyword: 'Ethiopia Tour Company',
    secondaryKeywords: ['Ethiopia Travel Agency', 'Local Ethiopia Tour Operator'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours',
    pageType: 'listing',
    primaryKeyword: 'Ethiopia Tour Packages',
    secondaryKeywords: ['Ethiopia Guided Tours', 'Private Ethiopia Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/destinations',
    pageType: 'listing',
    primaryKeyword: 'Ethiopia Travel Destinations',
    secondaryKeywords: ['Places to Visit in Ethiopia', 'Ethiopia Destinations'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/about',
    pageType: 'company',
    primaryKeyword: 'About Ethio Origins Tour',
    secondaryKeywords: ['Local Ethiopia Tour Operator', 'Ethiopia Travel Experts'],
    searchIntent: 'navigational',
    indexable: true,
  },
  {
    route: '/contact',
    pageType: 'company',
    primaryKeyword: 'Contact Ethio Origins Tour',
    secondaryKeywords: ['Plan an Ethiopia Tour', 'Ethiopia Tour Inquiry'],
    searchIntent: 'transactional',
    indexable: true,
  },
  {
    route: '/gallery',
    pageType: 'listing',
    primaryKeyword: 'Ethiopia Travel Gallery',
    secondaryKeywords: ['Ethiopia Tour Photos', 'Ethiopia Destination Photography'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/blog',
    pageType: 'blog',
    primaryKeyword: 'Ethiopia Travel Guide',
    secondaryKeywords: ['Ethiopia Travel Tips', 'Ethiopia Travel Planning'],
    searchIntent: 'informational',
    indexable: true,
    notes: 'Blog detail pages remain unpublished until complete approved article bodies exist.',
  },
  {
    route: '/tours/ethiopia-historic-route-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Historic Route Tours',
    secondaryKeywords: ['Northern Ethiopia Historical Tour', 'Bahir Dar Gondar Lalibela Aksum Tour'],
    searchIntent: 'commercial',
    indexable: true,
    notes: 'Broad historic-route target; tour details target duration-specific routes.',
  },
  {
    route: '/tours/day-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Day Tours',
    secondaryKeywords: ['Addis Ababa Day Tour', 'Ethiopia Day Trips'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/cultural-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Cultural Tours',
    secondaryKeywords: ['Omo Valley Cultural Tours', 'Ethiopia Heritage Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/omo-valley-tours',
    pageType: 'category',
    primaryKeyword: 'Omo Valley Tours',
    secondaryKeywords: ['Omo Valley Cultural Tours', 'Southern Ethiopia Tours'],
    searchIntent: 'commercial',
    indexable: true,
    notes: 'Broad Omo Valley target; detail pages target duration and route combinations.',
  },
  {
    route: '/tours/historical-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Historical Tours',
    secondaryKeywords: ['Ethiopia Heritage Tours', 'Historical Tour Packages Ethiopia'],
    searchIntent: 'commercial',
    indexable: true,
    notes: 'Broader heritage-tour target; historic-route category targets the named northern circuit.',
  },
  {
    route: '/tours/religious-pilgrimage-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Religious Tours',
    secondaryKeywords: ['Ethiopia Pilgrimage Tours', 'Lalibela Pilgrimage Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/ethiopia-holiday-packages',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Holiday Packages',
    secondaryKeywords: ['Ethiopia Vacation Package', 'Ethiopia Cultural Holiday'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/nature-adventure-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Adventure Tours',
    secondaryKeywords: ['Ethiopia Nature Tours', 'Ethiopian Adventure Travel'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/southern-ethiopia-tours',
    pageType: 'category',
    primaryKeyword: 'Southern Ethiopia Tour',
    secondaryKeywords: ['Omo Valley and Bale Mountains Adventure'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/nature-geological-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Geological Tours',
    secondaryKeywords: ['Danakil Depression Tours', 'Erta Ale Volcano Tour'],
    searchIntent: 'commercial',
    indexable: true,
    notes: 'Broad geological-tour target; Danakil packages target specific duration combinations.',
  },
  {
    route: '/tours/wildlife-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Wildlife Tours',
    secondaryKeywords: ['Endemic Wildlife Ethiopia', 'Ethiopia Wildlife Safaris'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/photography-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Photography Tours',
    secondaryKeywords: ['Ethiopia Photo Tours', 'Omo Valley Photography Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/city-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Sightseeing Tours',
    secondaryKeywords: ['Ethiopia City Tours', 'Addis Ababa City Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/unesco-heritage-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia UNESCO Heritage Tours',
    secondaryKeywords: ['Harar UNESCO Tour', 'Historic Ethiopia Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/private-customized-tours',
    pageType: 'category',
    primaryKeyword: 'Private Tours Ethiopia',
    secondaryKeywords: ['Ethiopia Customized Tours', 'Tailor-Made Ethiopia Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/destinations/omo-valley',
    pageType: 'destination',
    primaryKeyword: 'Omo Valley Travel Guide',
    secondaryKeywords: ['Omo Valley Ethiopia Travel', 'Southern Ethiopia Cultural Tours'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/destinations/danakil-depression',
    pageType: 'destination',
    primaryKeyword: 'Danakil Depression Tours',
    secondaryKeywords: ['Dallol Tour Ethiopia', 'Erta Ale Volcano Tour'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/destinations/lalibela',
    pageType: 'destination',
    primaryKeyword: 'Lalibela Tours',
    secondaryKeywords: ['Lalibela Rock-Hewn Churches', 'Lalibela Ethiopia Travel'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/destinations/wenchi-crater-lake',
    pageType: 'destination',
    primaryKeyword: 'Wenchi Crater Lake Tours',
    secondaryKeywords: ['Wenchi Day Trip', 'Wenchi Crater Lake Retreat'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/destinations/bale-mountains-national-park',
    pageType: 'destination',
    primaryKeyword: 'Bale Mountains Tours',
    secondaryKeywords: ['Bale Mountains Wildlife Tour', 'Bale Mountains Trekking'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/destinations/awash-national-park',
    pageType: 'destination',
    primaryKeyword: 'Awash National Park Tours',
    secondaryKeywords: ['Awash Wildlife Tour', 'Awash Hot Springs Tour'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/tours/4-day-danakil-depression-erta-ale-tour',
    pageType: 'tour',
    primaryKeyword: '4 Day Danakil Depression Tour',
    secondaryKeywords: ['Erta Ale Volcano Tour', 'Dallol Tour Ethiopia'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/8-day-omo-valley-cultural-discovery-tour',
    pageType: 'tour',
    primaryKeyword: '8 Day Omo Valley Cultural Tour',
    secondaryKeywords: ['Omo Valley Cultural Discovery', 'Southern Ethiopia Cultural Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/10-day-omo-valley-bale-mountains-cultural-adventure',
    pageType: 'tour',
    primaryKeyword: '10 Day Omo Valley and Bale Mountains Tour',
    secondaryKeywords: ['Omo Valley Bale Mountains Tour', 'Southern Ethiopia Wildlife Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/12-day-historic-north-omo-valley-tour',
    pageType: 'tour',
    primaryKeyword: '12 Day Historic North and Omo Valley Tour',
    secondaryKeywords: ['Northern Ethiopia and Omo Valley Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/3-day-lalibela-genna-festival-tour',
    pageType: 'tour',
    primaryKeyword: '3 Day Lalibela Christmas Tour',
    secondaryKeywords: ['Lalibela Genna Festival Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/20-day-ethiopia-historical-cultural-adventure',
    pageType: 'tour',
    primaryKeyword: '20 Day Ethiopia Historical and Cultural Tour',
    secondaryKeywords: ['Northern Ethiopia Harar Tour', 'Ethiopia Cultural Adventure'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/6-day-ethiopia-holiday-package',
    pageType: 'tour',
    primaryKeyword: '6 Day Ethiopia Holiday Package',
    secondaryKeywords: ['Ethiopia Vacation Package', 'Northern Ethiopia Holiday Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/1-day-debre-libanos-portuguese-bridge-tour',
    pageType: 'tour',
    primaryKeyword: 'Debre Libanos Day Tour',
    secondaryKeywords: ['Portuguese Bridge Tour', 'Addis Ababa Day Trip'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/5-day-lalibela-danakil-depression-tour',
    pageType: 'tour',
    primaryKeyword: '5 Day Lalibela and Danakil Tour',
    secondaryKeywords: ['Lalibela Danakil Tour', 'Erta Ale and Lalibela Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/3-day-harar-cultural-historical-tour',
    pageType: 'tour',
    primaryKeyword: '3 Day Harar Tour',
    secondaryKeywords: ['Harar Cultural Tour', 'Harar Historical Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/addis-ababa-full-day-city-tour',
    pageType: 'tour',
    primaryKeyword: 'Addis Ababa Full-Day City Tour',
    secondaryKeywords: ['Addis Ababa City Tour', 'Addis Ababa Sightseeing Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/wonchi-crater-lake-day-tour',
    pageType: 'tour',
    primaryKeyword: 'Wonchi Crater Lake Day Tour',
    secondaryKeywords: ['Wonchi Day Trip from Addis Ababa'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/5-day-ethiopia-historic-route-tour',
    pageType: 'tour',
    primaryKeyword: '5 Day Ethiopia Historic Route Tour',
    secondaryKeywords: ['Bahir Dar Gondar Lalibela Aksum Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/27-day-ethiopian-history-nature-culture-adventure',
    pageType: 'tour',
    primaryKeyword: '27 Day Grand Ethiopia Tour',
    secondaryKeywords: ['Ethiopia History Nature Culture Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/14-day-ethiopia-historic-route-danakil-depression',
    pageType: 'tour',
    primaryKeyword: '14 Day Ethiopia Historic Route Tour',
    secondaryKeywords: ['Northern Ethiopia Historic Route Tour'],
    searchIntent: 'commercial',
    indexable: true,
    notes: 'Approved title includes Danakil; current approved itinerary does not.',
  },
]

export function getContentKeywordTarget(route: string) {
  return contentKeywordTargets.find((target) => target.route === route)
}
