export type ContentKeywordTarget = {
  route: string
  pageType:
    | 'home'
    | 'listing'
    | 'category'
    | 'tour'
    | 'destination'
    | 'blog'
    | 'company'
  primaryKeyword: string
  secondaryKeywords: string[]
  searchIntent:
    | 'commercial'
    | 'transactional'
    | 'informational'
    | 'navigational'
  indexable: boolean
  notes?: string
}

export const requiredCommercialKeywords = [
  'Ethio Origin Tour', 'Ethio Origin Tours', 'Ethiopia Tour Company',
  'Best Tour Operator in Ethiopia', 'Ethiopia Travel Agency', 'Ethiopia Vacation Packages',
  'Ethiopia Cultural Tours', 'Ethiopia Historical Tours', 'Ethiopia Adventure Tours',
  'Ethiopia Sightseeing Tours', 'Ethiopia Travel Packages', 'Addis Ababa City Tours',
  'Ethiopia Holiday Packages', 'Local Tour Guides in Ethiopia', 'Ethiopia Group Tours',
  'Private Tours Ethiopia', 'Ethiopia Travel Experts', 'Ethiopia Heritage Tours',
  'Ethiopia Nature Tours', 'Ethiopia Tourism Company', 'Affordable Ethiopia Tours',
  'Ethiopia Customized Tours', 'Ethiopia Travel Planner', 'Ethiopia Tour Packages',
  'Ethiopia Cultural Experiences', 'Lalibela Tour Packages', 'Simien Mountains Tours',
  'Danakil Depression Tours', 'Omo Valley Tours', 'Gondar Historical Tours',
  'Axum Tours Ethiopia', 'Ethiopia Trekking Tours', 'Ethiopia Photography Tours',
  'Ethiopia Family Vacations', 'Ethiopia Honeymoon Tours', 'Ethiopia Eco Tours',
  'Ethiopia Wildlife Tours', 'Ethiopia Guided Tours', 'Ethiopia Luxury Tours',
  'Ethiopia Budget Tours', 'Ethiopia Travel and Tourism', 'Ethiopian Adventure Travel',
  'Explore Ethiopia Tours', 'Visit Ethiopia Package', 'Ethiopia Holiday Planner',
  'Ethiopia Travel Services', 'Top Tour Companies in Ethiopia',
  'Trusted Ethiopian Tour Operator', 'Ethiopia Tour Booking',
  'Ethio Origin Travel and Tours',
] as const

export const contentKeywordTargets: ContentKeywordTarget[] = [
  {
    route: '/',
    pageType: 'home',
    primaryKeyword: 'Ethiopia Tour Company',
    secondaryKeywords: [
      'Ethio Origin Tour', 'Ethio Origin Tours', 'Ethio Origin Travel and Tours',
      'Ethiopia Travel Agency', 'Best Tour Operator in Ethiopia',
      'Top Tour Companies in Ethiopia', 'Trusted Ethiopian Tour Operator',
      'Ethiopia Tourism Company', 'Ethiopia Travel Experts',
      'Ethiopia Travel Services', 'Local Tour Guides in Ethiopia',
    ],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours',
    pageType: 'listing',
    primaryKeyword: 'Ethiopia Tour Packages',
    secondaryKeywords: [
      'Ethiopia Vacation Packages', 'Ethiopia Travel Packages',
      'Ethiopia Guided Tours', 'Ethiopia Group Tours', 'Ethiopia Family Vacations',
      'Ethiopia Honeymoon Tours', 'Ethiopia Luxury Tours', 'Ethiopia Budget Tours',
      'Ethiopia Travel and Tourism', 'Explore Ethiopia Tours', 'Visit Ethiopia Package',
      'Ethiopia Tour Booking',
    ],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/destinations',
    pageType: 'listing',
    primaryKeyword: 'Ethiopia Travel Destinations',
    secondaryKeywords: ['Places to Visit in Ethiopia', 'Ethiopia Destinations'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/about',
    pageType: 'company',
    primaryKeyword: 'About Ethio Origins Tour',
    secondaryKeywords: ['Local Ethiopia Tour Operator', 'Ethiopia Travel Experts'],
    searchIntent: 'navigational',
    indexable: true,
  },
  {
    route: '/contact',
    pageType: 'company',
    primaryKeyword: 'Ethiopia Customized Tours',
    secondaryKeywords: [
      'Contact Ethio Origins Tour', 'Plan an Ethiopia Tour', 'Ethiopia Tour Inquiry',
      'Ethiopia Travel Planner', 'Ethiopia Travel Experts', 'Private Tours Ethiopia',
      'Ethiopia Travel Services',
    ],
    searchIntent: 'transactional',
    indexable: true,
  },
  {
    route: '/terms',
    pageType: 'company',
    primaryKeyword: 'Ethio Origins Tour Terms and Conditions',
    secondaryKeywords: ['Ethiopia Tour Booking Terms'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/privacy',
    pageType: 'company',
    primaryKeyword: 'Ethio Origins Tour Privacy Policy',
    secondaryKeywords: ['Ethio Origins Data Privacy'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/gallery',
    pageType: 'listing',
    primaryKeyword: 'Ethiopia Travel Gallery',
    secondaryKeywords: ['Ethiopia Tour Photos', 'Ethiopia Destination Photography'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/blog',
    pageType: 'blog',
    primaryKeyword: 'Ethiopia Travel Guide',
    secondaryKeywords: ['Ethiopia Travel Tips', 'Ethiopia Travel Planning'],
    searchIntent: 'informational',
    indexable: true,
    notes: 'Blog detail pages remain unpublished until complete approved article bodies exist.',
  },
  {
    route: '/tours/ethiopia-historic-route-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Historic Route Tours',
    secondaryKeywords: ['Northern Ethiopia Historical Tour', 'Bahir Dar Gondar Lalibela Axum Tour'],
    searchIntent: 'commercial',
    indexable: true,
    notes: 'Broad historic-route target; tour details target duration-specific routes.',
  },
  {
    route: '/tours/day-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Day Tours',
    secondaryKeywords: ['Addis Ababa Day Tour', 'Ethiopia Day Trips'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/cultural-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Cultural Tours',
    secondaryKeywords: ['Omo Valley Cultural Tours', 'Ethiopia Heritage Tours', 'Ethiopia Cultural Experiences'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/omo-valley-tours',
    pageType: 'category',
    primaryKeyword: 'Omo Valley Tours',
    secondaryKeywords: ['Omo Valley Cultural Tours', 'Southern Ethiopia Tours'],
    searchIntent: 'commercial',
    indexable: true,
    notes: 'Broad Omo Valley target; detail pages target duration and route combinations.',
  },
  {
    route: '/tours/historical-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Historical Tours',
    secondaryKeywords: ['Ethiopia Heritage Tours', 'Historical Tour Packages Ethiopia'],
    searchIntent: 'commercial',
    indexable: true,
    notes: 'Broader heritage-tour target; historic-route category targets the named northern circuit.',
  },
  {
    route: '/tours/religious-pilgrimage-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Religious Tours',
    secondaryKeywords: ['Ethiopia Pilgrimage Tours', 'Lalibela Pilgrimage Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/ethiopia-holiday-packages',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Holiday Packages',
    secondaryKeywords: ['Ethiopia Vacation Package', 'Ethiopia Cultural Holiday', 'Ethiopia Holiday Planner'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/nature-adventure-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Adventure Tours',
    secondaryKeywords: [
      'Ethiopia Nature Tours', 'Ethiopian Adventure Travel', 'Ethiopia Eco Tours',
      'Ethiopia Trekking Tours', 'Simien Mountains Tours',
    ],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/southern-ethiopia-tours',
    pageType: 'category',
    primaryKeyword: 'Southern Ethiopia Tour',
    secondaryKeywords: ['Omo Valley and Bale Mountains Adventure'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/nature-geological-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Geological Tours',
    secondaryKeywords: ['Danakil Depression Tours', 'Erta Ale Volcano Tour'],
    searchIntent: 'commercial',
    indexable: true,
    notes: 'Broad geological-tour target; Danakil packages target specific duration combinations.',
  },
  {
    route: '/tours/wildlife-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Wildlife Tours',
    secondaryKeywords: ['Endemic Wildlife Ethiopia', 'Ethiopia Wildlife Safaris'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/photography-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Photography Tours',
    secondaryKeywords: ['Ethiopia Photo Tours', 'Omo Valley Photography Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/city-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia Sightseeing Tours',
    secondaryKeywords: ['Ethiopia City Tours', 'Addis Ababa City Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/unesco-heritage-tours',
    pageType: 'category',
    primaryKeyword: 'Ethiopia UNESCO Heritage Tours',
    secondaryKeywords: [
      'Harar UNESCO Tour', 'Historic Ethiopia Tours', 'Lalibela Tour Packages',
      'Gondar Historical Tours', 'Axum Tours Ethiopia',
    ],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/private-customized-tours',
    pageType: 'category',
    primaryKeyword: 'Private Tours Ethiopia',
    secondaryKeywords: [
      'Ethiopia Customized Tours', 'Tailor-Made Ethiopia Tours',
      'Ethiopia Travel Planner', 'Affordable Ethiopia Tours',
    ],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/destinations/omo-valley',
    pageType: 'destination',
    primaryKeyword: 'Omo Valley Travel Guide',
    secondaryKeywords: ['Omo Valley Ethiopia Travel', 'Southern Ethiopia Cultural Tours'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/destinations/danakil-depression',
    pageType: 'destination',
    primaryKeyword: 'Danakil Depression Tours',
    secondaryKeywords: ['Dallol Tour Ethiopia', 'Erta Ale Volcano Tour'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/destinations/lalibela',
    pageType: 'destination',
    primaryKeyword: 'Lalibela Tour Packages',
    secondaryKeywords: ['Lalibela Tours', 'Lalibela Rock-Hewn Churches', 'Lalibela Ethiopia Travel'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/destinations/addis-ababa',
    pageType: 'destination',
    primaryKeyword: 'Addis Ababa City Tours',
    secondaryKeywords: ['Addis Ababa Sightseeing Tours', 'Ethiopia City Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/destinations/gondar',
    pageType: 'destination',
    primaryKeyword: 'Gondar Historical Tours',
    secondaryKeywords: ['Gondar Castle Tour', 'Northern Ethiopia Historical Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/destinations/aksum',
    pageType: 'destination',
    primaryKeyword: 'Axum Tours Ethiopia',
    secondaryKeywords: ['Axum Historical Tours', 'Northern Ethiopia Heritage Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/destinations/simien-mountains-national-park',
    pageType: 'destination',
    primaryKeyword: 'Simien Mountains Tours',
    secondaryKeywords: ['Simien Mountains Trekking', 'Ethiopia Trekking Tours'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/destinations/wenchi-crater-lake',
    pageType: 'destination',
    primaryKeyword: 'Wenchi Crater Lake Tours',
    secondaryKeywords: ['Wenchi Day Trip', 'Wenchi Crater Lake Retreat'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/destinations/bale-mountains-national-park',
    pageType: 'destination',
    primaryKeyword: 'Bale Mountains Tours',
    secondaryKeywords: ['Bale Mountains Wildlife Tour', 'Bale Mountains Trekking'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/destinations/awash-national-park',
    pageType: 'destination',
    primaryKeyword: 'Awash National Park Tours',
    secondaryKeywords: ['Awash Wildlife Tour', 'Awash Hot Springs Tour'],
    searchIntent: 'informational',
    indexable: true,
  },
  {
    route: '/tours/4-day-danakil-depression-erta-ale-tour',
    pageType: 'tour',
    primaryKeyword: '4 Day Danakil Depression Tour',
    secondaryKeywords: ['Erta Ale Volcano Tour', 'Dallol Tour Ethiopia'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/8-day-omo-valley-cultural-discovery-tour',
    pageType: 'tour',
    primaryKeyword: '8 Day Omo Valley Cultural Tour',
    secondaryKeywords: ['Omo Valley Cultural Discovery', 'Southern Ethiopia Cultural Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/10-day-omo-valley-bale-mountains-cultural-adventure',
    pageType: 'tour',
    primaryKeyword: '10 Day Omo Valley and Bale Mountains Tour',
    secondaryKeywords: ['Omo Valley Bale Mountains Tour', 'Southern Ethiopia Wildlife Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/12-day-historic-north-omo-valley-tour',
    pageType: 'tour',
    primaryKeyword: '12 Day Historic North and Omo Valley Tour',
    secondaryKeywords: ['Northern Ethiopia and Omo Valley Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/3-day-lalibela-genna-festival-tour',
    pageType: 'tour',
    primaryKeyword: '3 Day Lalibela Christmas Tour',
    secondaryKeywords: ['Lalibela Genna Festival Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/20-day-ethiopia-historical-cultural-adventure',
    pageType: 'tour',
    primaryKeyword: '20 Day Ethiopia Historical and Cultural Tour',
    secondaryKeywords: ['Northern Ethiopia Harar Tour', 'Ethiopia Cultural Adventure'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/6-day-ethiopia-holiday-package',
    pageType: 'tour',
    primaryKeyword: '6 Day Ethiopia Holiday Package',
    secondaryKeywords: ['Ethiopia Vacation Package', 'Northern Ethiopia Holiday Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/1-day-debre-libanos-portuguese-bridge-tour',
    pageType: 'tour',
    primaryKeyword: 'Debre Libanos Day Tour',
    secondaryKeywords: ['Portuguese Bridge Tour', 'Addis Ababa Day Trip'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/5-day-lalibela-danakil-depression-tour',
    pageType: 'tour',
    primaryKeyword: '5 Day Lalibela and Danakil Tour',
    secondaryKeywords: ['Lalibela Danakil Tour', 'Erta Ale and Lalibela Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/3-day-harar-cultural-historical-tour',
    pageType: 'tour',
    primaryKeyword: '3 Day Harar Tour',
    secondaryKeywords: ['Harar Cultural Tour', 'Harar Historical Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/addis-ababa-full-day-city-tour',
    pageType: 'tour',
    primaryKeyword: 'Addis Ababa Full-Day City Tour',
    secondaryKeywords: ['Addis Ababa City Tour', 'Addis Ababa Sightseeing Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/wonchi-crater-lake-day-tour',
    pageType: 'tour',
    primaryKeyword: 'Wonchi Crater Lake Day Tour',
    secondaryKeywords: ['Wonchi Day Trip from Addis Ababa'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/5-day-ethiopia-historic-route-tour',
    pageType: 'tour',
    primaryKeyword: '5 Day Ethiopia Historic Route Tour',
    secondaryKeywords: ['Bahir Dar Gondar Lalibela Axum Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/27-day-ethiopian-history-nature-culture-adventure',
    pageType: 'tour',
    primaryKeyword: '27 Day Grand Ethiopia Tour',
    secondaryKeywords: ['Ethiopia History Nature Culture Tour'],
    searchIntent: 'commercial',
    indexable: true,
  },
  {
    route: '/tours/14-day-ethiopia-historic-route-danakil-depression',
    pageType: 'tour',
    primaryKeyword: '14 Day Ethiopia Historic Route Tour',
    secondaryKeywords: ['Northern Ethiopia Historic Route Tour'],
    searchIntent: 'commercial',
    indexable: true,
    notes: 'Approved title includes Danakil; current approved itinerary does not.',
  },
]

export function getContentKeywordTarget(route: string) {
  return contentKeywordTargets.find((target) => target.route === route)
}
